image: maven:3.8.4-openjdk-17

cache:
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn clean compile
  tags:
    - GAUFRE_RUNNER

test:
  stage: test
  script:
    - mvn test
  tags:
    - GAUFRE_RUNNER

deploy:
  stage: deploy
  only:
    - tags
  script:
    - echo "Deploying...."
    - |
      curl --request POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"\
           --header "Content-Type: application/json" \
           --header "PRIVATE-TOKEN: ${release_token}" \
           --data "{
              \"tag_name\": \"${CI_COMMIT_TAG}\",
              \"name\": \"${CI_COMMIT_TAG}\",
              \"ref\": \"${CI_COMMIT_TAG}\",
              \"description\": \"## Release : ${CI_COMMIT_TAG}\",
              \"assets\": {}
              }"
    - echo "release successfully done"
  tags:
    - GAUFRE_RUNNER
